name       : python-slowaes
version    : 0.1
release    : 3
source     :
    - https://pypi.python.org/packages/79/a4/c7dcbe89ec22a6985790bc0effb12bb8caef494fbac3c2bab86ae51a53ef/slowaes-0.1a1.tar.gz : 83658ae54cc116b96f7fdb12fdd0efac3a4e8c7c7064e3fac3f4a881aa54bf09
license    : Apache-2.0
component  : programming.python
summary    : Implementation of AES in Python
description: |
    Implementation of AES in Python
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
